extends Node


var Card_Asset_Basic_Stats = { # all card divided by id
	0: {
		"health" : 1,
		"attack" : 0,
		"speed" : 0,
		"weight" : 0,
		"cost" : 0,
		"name" : "",
		"gene" : "",
		"deviation" : "",
		"type" : "",
		"effect" : "",
		"effect_type" : "",
		"base" : "Base",
		"baseid" : [],
		"cae" : true,
		"cal" : true,
		"ptm" : 0,
		"mi" : 0,
		"can_move": true,
		"can_ability": true,
		"can_buf": true,
		"turn_blocked_on_play": 0
		},
	101: {
		"health" : 1,
		"attack" : 1,
		"speed" : 7,
		"weight" : 60,
		"cost" : 1,
		"name" : "Ordinary Citizen",
		"gene" : "Dwarf",
		"deviation" : "Standard",
		"type" : "Versatile",
		"effect" : "",
		"effect_type" : "",
		"base" : "Base",
		"baseid" : [],
		"cae" : true,
		"cal" : true,
		"ptm" : 0,
		"mi" : 0,
		"can_move": true,
		"can_ability": true,
		"can_buf": true,
		"turn_blocked_on_play": 0
		},
	102: {
		"health" : 2,
		"attack" : 2,
		"speed" : 7,
		"weight" : 59,
		"cost" : 1,
		"name" : "Little Fighter",
		"gene" : "Dwarf",
		"deviation" : "Warrior",
		"type" : "Attack",
		"effect" : "",
		"effect_type" : "",
		"base" : "Base",
		"baseid" : [],
		"cae" : true,
		"cal" : true,
		"ptm" : 0,
		"mi" : 0,
		"can_move": true,
		"can_ability": true,
		"can_buf": true,
		"turn_blocked_on_play": 0
		},
	103: {
		"health" : 2,
		"attack" : 1,
		"speed" : 6,
		"weight" : 62,
		"cost" : 1,
		"name" : "String Observer",
		"gene" : "Dwarf",
		"deviation" : "Standard",
		"type" : "Defense",
		"effect" : "",
		"effect_type" : "",
		"base" : "Base",
		"baseid" : [],
		"cae" : true,
		"cal" : true,
		"ptm" : 0,
		"mi" : 0,
		"can_move": true,
		"can_ability": true,
		"can_buf": true,
		"turn_blocked_on_play": 0
		},
	104: {
		"health" : 1,
		"attack" : 4,
		"speed" : 6,
		"weight" : 39,
		"cost" : 2,
		"name" : "Baleful Fury",
		"gene" : "Dwarf",
		"deviation" : "Warrior",
		"type" : "Attack",
		"effect" : "After he attack, deal 1 damage to 1 another card on enemy field",
		"effect_type" : "Rage",
		"base" : "Base",
		"baseid" : [],
		"cae" : true,
		"cal" : true,
		"ptm" : 0,
		"mi" : 0,
		"can_move": true,
		"can_ability": true,
		"can_buf": true,
		"turn_blocked_on_play": 0
		},
	105: {
		"health" : 2,
		"attack" : 2,
		"speed" : 8,
		"weight" : 71,
		"cost" : 2,
		"name" : "Peak Reacher",
		"gene" : "Dwarf",
		"deviation" : "Warrior",
		"type" : "Versatile",
		"effect" : "",
		"effect_type" : "",
		"base" : "Base",
		"baseid" : [],
		"cae" : true,
		"cal" : true,
		"ptm" : 0,
		"mi" : 0,
		"can_move": true,
		"can_ability": true,
		"can_buf": true,
		"turn_blocked_on_play": 0
		},
	106: {
		"health" : 4,
		"attack" : 1,
		"speed" : 5,
		"weight" : 71,
		"cost" : 2,
		"name" : "Angry Scientist",
		"gene" : "Dwarf",
		"deviation" : "Sage",
		"type" : "Versatile",
		"effect" : "When you draw a card gain +1 attack",
		"effect_type" : "OnDraw",
		"base" : "Base",
		"baseid" : [],
		"cae" : true,
		"cal" : true,
		"ptm" : 0,
		"mi" : 0,
		"can_move": true,
		"can_ability": true,
		"can_buf": true,
		"turn_blocked_on_play": 0
		},
	107: {
		"health" : 3,
		"attack" : 2,
		"speed" : 2,
		"weight" : 80,
		"cost" : 2,
		"name" : "Brute",
		"gene" : "Dwarf",
		"deviation" : "Miner",
		"type" : "Defense",
		"effect" : "",
		"effect_type" : "",
		"base" : "Base",
		"baseid" : [],
		"cae" : true,
		"cal" : true,
		"ptm" : 0,
		"mi" : 0,
		"can_move": true,
		"can_ability": true,
		"can_buf": true,
		"turn_blocked_on_play": 0
		},
	108: {
		"health" : 2,
		"attack" : 2,
		"speed" : 6,
		"weight" : 71,
		"cost" : 3,
		"name" : "Call Of The Forest",
		"gene" : "Dwarf",
		"deviation" : "Warrior",
		"type" : "Attack",
		"effect" : "When played give +2 attack to one another dwarf",
		"effect_type" : "Rise",
		"base" : "Base",
		"baseid" : [],
		"cae" : true,
		"cal" : true,
		"ptm" : 0,
		"mi" : 0,
		"can_move": true,
		"can_ability": true,
		"can_buf": true,
		"turn_blocked_on_play": 0
		},
	109: {
		"health" : 2,
		"attack" : 6,
		"speed" : 8,
		"weight" : 39,
		"cost" : 3,
		"name" : "Last Chance",
		"gene" : "Dwarf",
		"deviation" : "Warrior",
		"type" : "Attack",
		"effect" : "When he attack he dies",
		"effect_type" : "Rage",
		"base" : "Base",
		"baseid" : [],
		"cae" : true,
		"cal" : true,
		"ptm" : 0,
		"mi" : 0,
		"can_move": true,
		"can_ability": true,
		"can_buf": true,
		"turn_blocked_on_play": 0
		},
	110: {
		"health" : 3,
		"attack" : 3,
		"speed" : 6,
		"weight" : 48,
		"cost" : 3,
		"name" : "Rob The Builder",
		"gene" : "Dwarf",
		"deviation" : "Standard",
		"type" : "Versatile",
		"effect" : "",
		"effect_type" : "",
		"base" : "Base",
		"baseid" : [],
		"cae" : true,
		"cal" : true,
		"ptm" : 0,
		"mi" : 0,
		"can_move": true,
		"can_ability": true,
		"can_buf": true,
		"turn_blocked_on_play": 0
		},
	111: {
		"health" : 2,
		"attack" : 5,
		"speed" : 9,
		"weight" : 70,
		"cost" : 3,
		"name" : "Animalist",
		"gene" : "Dwarf",
		"deviation" : "Warrior",
		"type" : "Attack",
		"effect" : "If he perform the first attack he gain +1 health",
		"effect_type" : "Rage",
		"base" : "Base",
		"baseid" : [],
		"cae" : true,
		"cal" : true,
		"ptm" : 0,
		"mi" : 0,
		"can_move": true,
		"can_ability": true,
		"can_buf": true,
		"turn_blocked_on_play": 0
		},
	112: {
		"health" : 4,
		"attack" : 3,
		"speed" : 6,
		"weight" : 45,
		"cost" : 3,
		"name" : "Corrupted Baby",
		"gene" : "Dwarf",
		"deviation" : "Standard",
		"type" : "Defense",
		"effect" : "Phase Mutation (8)",
		"effect_type" : "Phase Mutation",
		"base" : "Base",
		"baseid" : [],
		"cae" : true,
		"cal" : true,
		"ptm" : 8,
		"mi" : 113,
		"can_move": true,
		"can_ability": true,
		"can_buf": true,
		"turn_blocked_on_play": 0
		},
	113: {
		"health" : 4,
		"attack" : 5,
		"speed" : 7,
		"weight" : 47,
		"cost" : 3,
		"name" : "Famelic Kid",
		"gene" : "Dwarf",
		"deviation" : "Warrior",
		"type" : "Versatile",
		"effect" : "He can't attack enemy leader",
		"effect_type" : "",
		"base" : "Base",
		"baseid" : [],
		"cae" : true,
		"cal" : false,
		"ptm" : 0,
		"mi" : 0,
		"can_move": true,
		"can_ability": true,
		"can_buf": true,
		"turn_blocked_on_play": 0
		},
	114: {
		"health" : 3,
		"attack" : 4,
		"speed" : 6,
		"weight" : 84,
		"cost" : 3,
		"name" : "Light on the dark",
		"gene" : "Dwarf",
		"deviation" : "Warrior",
		"type" : "Attack",
		"effect" : "Reveal one random card from enemy hand",
		"effect_type" : "Rise",
		"base" : "Base",
		"baseid" : [],
		"cae" : true,
		"cal" : true,
		"ptm" : 0,
		"mi" : 0,
		"can_move": true,
		"can_ability": true,
		"can_buf": true,
		"turn_blocked_on_play": 0
		},
	115: {
		"health" : 6,
		"attack" : 1,
		"speed" : 7,
		"weight" : 89,
		"cost" : 5,
		"name" : "Rail Dwarf",
		"gene" : "Dwarf",
		"deviation" : "Miner",
		"type" : "Versatile",
		"effect" : "When he's attacked give +2 attack to two of your dwarfs",
		"effect_type" : "Rage",
		"base" : "Base",
		"baseid" : [],
		"cae" : true,
		"cal" : true,
		"ptm" : 0,
		"mi" : 0,
		"can_move": true,
		"can_ability": true,
		"can_buf": true,
		"turn_blocked_on_play": 0
		},
	116: {
		"health" : 5,
		"attack" : 2,
		"speed" : 5,
		"weight" : 72,
		"cost" : 4,
		"name" : "Sapient Waiter",
		"gene" : "Dwarf",
		"deviation" : "Miner",
		"type" : "Attack",
		"effect" : "When someone plays a card he gain +1 attack",
		"effect_type" : "OnDeploy",
		"base" : "Base",
		"baseid" : [],
		"cae" : true,
		"cal" : true,
		"ptm" : 0,
		"mi" : 0,
		"can_move": true,
		"can_ability": true,
		"can_buf": true,
		"turn_blocked_on_play": 0
		},
	117: {
		"health" : 4,
		"attack" : 4,
		"speed" : 5,
		"weight" : 76,
		"cost" : 4,
		"name" : "Unstable Fighter",
		"gene" : "Dwarf",
		"deviation" : "Standard",
		"type" : "Attack",
		"effect" : "Phase Mutation (5)",
		"effect_type" : "Phase Mutation",
		"base" : "Base",
		"baseid" : [],
		"cae" : true,
		"cal" : true,
		"ptm" : 5,
		"mi" : 118,
		"can_move": true,
		"can_ability": true,
		"can_buf": true,
		"turn_blocked_on_play": 0
		},
	118: {
		"health" : 5,
		"attack" : 3,
		"speed" : 6,
		"weight" : 76,
		"cost" : 4,
		"name" : "Shaky Warrior",
		"gene" : "Dwarf",
		"deviation" : "Warrior",
		"type" : "Attack",
		"effect" : "When enemy turn starts gain +1 attack",
		"effect_type" : "onTurnBegin",
		"base" : "Base",
		"baseid" : [],
		"cae" : true,
		"cal" : true,
		"ptm" : 0,
		"mi" : 0,
		"can_move": true,
		"can_ability": true,
		"can_buf": true,
		"turn_blocked_on_play": 0
		},
	119: {
		"health" : 4,
		"attack" : 4,
		"speed" : 4,
		"weight" : 80,
		"cost" : 5,
		"name" : "Self-Centered Guy",
		"gene" : "Dwarf",
		"deviation" : "Standard",
		"type" : "Attack",
		"effect" : "When someone plays a dwarf gain +1 attack and +1 health",
		"effect_type" : "OnDeploy",
		"base" : "Shaky Warrior",
		"baseid" : [118],
		"cae" : true,
		"cal" : true,
		"ptm" : 0,
		"mi" : 0,
		"can_move": true,
		"can_ability": true,
		"can_buf": true,
		"turn_blocked_on_play": 0
		},
	120: {
		"health" : 6,
		"attack" : 3,
		"speed" : 5,
		"weight" : 46,
		"cost" : 5,
		"name" : "White Beard",
		"gene" : "Dwarf",
		"deviation" : "Warrior",
		"type" : "Versatile",
		"effect" : "",
		"effect_type" : "",
		"base" : "Base",
		"baseid" : [],
		"cae" : true,
		"cal" : true,
		"ptm" : 0,
		"mi" : 0,
		"can_move": true,
		"can_ability": true,
		"can_buf": true,
		"turn_blocked_on_play": 0
		},
	121: {
		"health" : 3,
		"attack" : 6,
		"speed" : 5,
		"weight" : 47,
		"cost" : 5,
		"name" : "Dark Beard",
		"gene" : "Dwarf",
		"deviation" : "Warrior",
		"type" : "Versatile",
		"effect" : "",
		"effect_type" : "",
		"base" : "Base",
		"baseid" : [],
		"cae" : true,
		"cal" : true,
		"ptm" : 0,
		"mi" : 0,
		"can_move": true,
		"can_ability": true,
		"can_buf": true,
		"turn_blocked_on_play": 0
		},
	122: {
		"health" : 6,
		"attack" : 5,
		"speed" : 6,
		"weight" : 71,
		"cost" : 6,
		"name" : "Dwarf Doctor",
		"gene" : "Dwarf",
		"deviation" : "Miner",
		"type" : "Defense",
		"effect" : "When played give +2 attack to one another dwarf on your field and +1 health to 2 other dwarf on your field",
		"effect_type" : "Rise",
		"base" : "Base",
		"baseid" : [],
		"cae" : true,
		"cal" : true,
		"ptm" : 0,
		"mi" : 0,
		"can_move": true,
		"can_ability": true,
		"can_buf": true,
		"turn_blocked_on_play": 0
		},
	123: {
		"health" : 5,
		"attack" : 6,
		"speed" : 6,
		"weight" : 83,
		"cost" : 6,
		"name" : "Retired Sniper",
		"gene" : "Dwarf",
		"deviation" : "Warrior",
		"type" : "Attack",
		"effect" : "When played do 1 damage to 3 different enemy",
		"effect_type" : "Rise",
		"base" : "Base",
		"baseid" : [],
		"cae" : true,
		"cal" : true,
		"ptm" : 0,
		"mi" : 0,
		"can_move": true,
		"can_ability": true,
		"can_buf": true,
		"turn_blocked_on_play": 0
		},
	124: {
		"health" : 7,
		"attack" : 2,
		"speed" : 1,
		"weight" : 82,
		"cost" : 6,
		"name" : "Old Superior",
		"gene" : "Dwarf",
		"deviation" : "Sage",
		"type" : "Versatile",
		"effect" : "When enemy spends all the lymph draw a card and if it's a dwarf give it +1 attack, +1 health and reduce the cost by 1",
		"effect_type" : "OnDeploy",
		"base" : "Base",
		"baseid" : [],
		"cae" : true,
		"cal" : true,
		"ptm" : 0,
		"mi" : 0,
		"can_move": true,
		"can_ability": true,
		"can_buf": true,
		"turn_blocked_on_play": 0
		},
	125: {
		"health" : 5,
		"attack" : 2,
		"speed" : 2,
		"weight" : 76,
		"cost" : 7,
		"name" : "Holy Protector",
		"gene" : "Dwarf",
		"deviation" : "Sage",
		"type" : "Defense",
		"effect" : "When some other defense card uses the special give +1 attack and +1 health to all your card on the field and reduce by 1 the cost of 1 card in your hand",
		"effect_type" : "OnSpecial",
		"base" : "Base",
		"baseid" : [],
		"cae" : true,
		"cal" : true,
		"ptm" : 0,
		"mi" : 0,
		"can_move": true,
		"can_ability": true,
		"can_buf": true,
		"turn_blocked_on_play": 0
		},
	126: {
		"health" : 7,
		"attack" : 8,
		"speed" : 5,
		"weight" : 91,
		"cost" : 7,
		"name" : "Fool Dwarf",
		"gene" : "Dwarf",
		"deviation" : "Standard",
		"type" : "Versatile",
		"effect" : "When attacked he dies and kill who attacked him",
		"effect_type" : "Rage",
		"base" : "Base",
		"baseid" : [],
		"cae" : true,
		"cal" : true,
		"ptm" : 0,
		"mi" : 0,
		"can_move": true,
		"can_ability": true,
		"can_buf": true,
		"turn_blocked_on_play": 0
		},
	127: {
		"health" : 6,
		"attack" : 6,
		"speed" : 3,
		"weight" : 105,
		"cost" : 7,
		"name" : "Master Builder",
		"gene" : "Dwarf",
		"deviation" : "Miner",
		"type" : "Versatile",
		"effect" : "When one of your cards increment the attack stats gain +1 attack but if the card it's a dwarf also gain +1 health",
		"effect_type" : "OnBoost",
		"base" : "Base",
		"baseid" : [],
		"cae" : true,
		"cal" : true,
		"ptm" : 0,
		"mi" : 0,
		"can_move": true,
		"can_ability": true,
		"can_buf": true,
		"turn_blocked_on_play": 0
		},
	128: {
		"health" : 10,
		"attack" : 10,
		"speed" : 5,
		"weight" : 88,
		"cost" : 8,
		"name" : "Fate Walker",
		"gene" : "Dwarf",
		"deviation" : "Warrior",
		"type" : "Versatile",
		"effect" : "When attacked by an enemy will protect himself anyway",
		"effect_type" : "Rage",
		"base" : "White Beard / Dark Beard",
		"baseid" : [120, 121],
		"cae" : true,
		"cal" : true,
		"ptm" : 0,
		"mi" : 0,
		"can_move": true,
		"can_ability": true,
		"can_buf": true,
		"turn_blocked_on_play": 0
		},
	129: {
		"health" : 7,
		"attack" : 6,
		"speed" : 4,
		"weight" : 89,
		"cost" : 8,
		"name" : "Magic Miner",
		"gene" : "Dwarf",
		"deviation" : "Miner",
		"type" : "Defense",
		"effect" : "When you play a dwarf gives it +1 health",
		"effect_type" : "OnDeploy",
		"base" : "Base",
		"baseid" : [],
		"cae" : true,
		"cal" : true,
		"ptm" : 0,
		"mi" : 0,
		"can_move": true,
		"can_ability": true,
		"can_buf": true,
		"turn_blocked_on_play": 0
		},
	130: {
		"health" : 8,
		"attack" : 8,
		"speed" : 6,
		"weight" : 90,
		"cost" : 9,
		"name" : "War Declarer",
		"gene" : "Dwarf",
		"deviation" : "Warrior",
		"type" : "Versatile",
		"effect" : "If when played 4 or more dwarfs are present on the attack field, then gain +2 health and +2 attack",
		"effect_type" : "Rise",
		"base" : "Base",
		"baseid" : [],
		"cae" : true,
		"cal" : true,
		"ptm" : 0,
		"mi" : 0,
		"can_move": true,
		"can_ability": true,
		"can_buf": true,
		"turn_blocked_on_play": 0
		},
	131: {
		"health" : 5,
		"attack" : 6,
		"speed" : 10,
		"weight" : 128,
		"cost" : 9,
		"name" : "Hyenas Rider",
		"gene" : "Dwarf",
		"deviation" : "Warrior",
		"type" : "Attack",
		"effect" : "When he dies summon a Hyena 7/7/10/34",
		"effect_type" : "Heritage",
		"base" : "Base",
		"baseid" : [],
		"cae" : true,
		"cal" : true,
		"ptm" : 0,
		"mi" : 0,
		"can_move": true,
		"can_ability": true,
		"can_buf": true,
		"turn_blocked_on_play": 0
		},
	132: {
		"health" : 6,
		"attack" : 4,
		"speed" : 1,
		"weight" : 100,
		"cost" : 10,
		"name" : "Supreme Sage",
		"gene" : "Dwarf",
		"deviation" : "Sage",
		"type" : "Defense",
		"effect" : "Turn Mutation (6)",
		"effect_type" : "Turn Mutation",
		"base" : "Base",
		"baseid" : [],
		"cae" : true,
		"cal" : true,
		"ptm" : 6,
		"mi" : 133,
		"can_move": true,
		"can_ability": true,
		"can_buf": true,
		"turn_blocked_on_play": 0
		},
	133: {
		"health" : 10,
		"attack" : 6,
		"speed" : 5,
		"weight" : 2,
		"cost" : 10,
		"name" : "Inexorable Death",
		"gene" : "Dwarf",
		"deviation" : "Curse",
		"type" : "Defense",
		"effect" : "When an ally dwarf dies give one of your card +3 attack and +1 health",
		"effect_type" : "Revenge",
		"base" : "Base",
		"baseid" : [],
		"cae" : true,
		"cal" : true,
		"ptm" : 0,
		"mi" : 0,
		"can_move": true,
		"can_ability": true,
		"can_buf": true,
		"turn_blocked_on_play": 0
		},
}


func getCardInfo(id):
	return Card_Asset_Basic_Stats[id]

